INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (1, null, null, '404049', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (2, null, null, '211145', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (3, null, null, '202090', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (4, null, null, '215069', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (5, null, null, '184065', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (6, null, null, '207289', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (7, null, null, '218013', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (8, null, null, '216084', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (9, null, null, '210037', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (10, null, null, '185148', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (11, null, null, '208080', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (12, null, null, '203172', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (13, null, null, '209050', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (14, null, null, '208005', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (15, null, null, '217061', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (16, null, null, '201119', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (17, null, null, '410037', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (18, null, null, '208109', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (19, null, null, '204063', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (20, null, null, '184056', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (21, null, null, '210112', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (22, null, null, '202037', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (23, null, null, '208105', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (24, null, null, '217105', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (25, null, null, '413036', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (26, null, null, '210085', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (27, null, null, '407039', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (28, null, null, '200066', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (29, null, null, '202084', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (30, null, null, '187125', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (31, null, null, '213079', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (32, null, null, '416003', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (33, null, null, '193024', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (34, null, null, '415025', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (35, null, null, '186085', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (36, null, null, '214023', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (37, null, null, '214024', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (38, null, null, '199158', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (39, null, null, '216064', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (40, null, null, '408028', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (41, null, null, '216060', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (42, null, null, '206125', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (43, null, null, '211166', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (44, null, null, '183073', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (45, null, null, '415005', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (46, null, null, '195030', null, 0, 0, 0, 0, 1);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (47, null, null, '409029', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (48, null, null, '207337', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (49, null, null, '189113', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (50, null, null, '197104', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (51, null, null, '203145', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (52, null, null, '212031', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (53, null, null, '185173', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (54, null, null, '209009', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (55, null, null, '192213', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (56, null, null, '212049', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (57, null, null, '211163', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (58, null, null, '198001', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (59, null, null, '190214', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (60, null, null, '408041', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (61, null, null, '409024', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (62, null, null, '210060', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (63, null, null, '186050', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (64, null, null, '217075', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (65, null, null, '207330', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (66, null, null, '215017', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (67, null, null, '211203', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (68, null, null, '193033', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (69, null, null, '405058', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (70, null, null, '191225', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (71, null, null, '207336', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (72, null, null, '406048', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (73, null, null, '209128', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (74, null, null, '218099', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (75, null, null, '416017', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (76, null, null, '201121', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (77, null, null, '215019', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (78, null, null, '196021', null, 0, 0, 0, 0, 1);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (79, null, null, '414014', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (80, null, null, '212053', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (81, null, null, '214083', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (82, null, null, '203095', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (83, null, null, '193042', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (84, null, null, '410036', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (85, null, null, '218133', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (86, null, null, '200005', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (87, null, null, '414040', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (88, null, null, '209084', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (89, null, null, '213076', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (90, null, null, '211049', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (91, null, null, '203069', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (92, null, null, '208063', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (93, null, null, '205056', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (94, null, null, '218062', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (95, null, null, '209052', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (96, null, null, '404051', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (97, null, null, '218019', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (98, null, null, '213075', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (99, null, null, '203160', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (100, null, null, '209004', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (101, null, null, '207320', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (102, null, null, '198034', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (103, null, null, '187256', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (104, null, null, '217055', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (105, null, null, '216052', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (106, null, null, '217057', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (107, null, null, '218059', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (108, null, null, '197055', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (109, null, null, '213021', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (110, null, null, '198125', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (111, null, null, '215045', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (112, null, null, '413025', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (113, null, null, '181089', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (114, null, null, '211088', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (115, null, null, '217016', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (116, null, null, '218026', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (117, null, null, '198027', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (118, null, null, '211091', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (119, null, null, '198026', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (120, null, null, '200093', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (121, null, null, '412032', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (122, null, null, '212017', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (123, null, null, '205079', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (124, null, null, '199185', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (125, null, null, '216035', null, 0, 0, 0, 0, 0);/
INSERT INTO Member (num, kana_name, name, syain_num, lot_num, hit_flg, sanka_yotei_flg, sanka_flg, money_flg, hage_flg)  VALUES (126, null, null, '416016', null, 0, 0, 0, 0, 0);
